/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
/**
 *
 * @author lue
 */
public class Product extends javax.swing.JFrame {
    /**
     * Creates new form Product
     */
    String user = "root";
    String password = "admin";
    String db="jdbc:mysql://localhost/ybbom";
    Connection conn =null;
    Statement st = null;
    String prodCode  = "";
    
    DefaultListModel model = new DefaultListModel();
    DefaultListModel model1 = new DefaultListModel();
    
    public Product() {
        
        initComponents();
        category();
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Query(String query){
  
      try{
          conn = DriverManager.getConnection(db,user,password);
          st = conn.createStatement();
          st.executeUpdate(query);
          JOptionPane.showMessageDialog(null,"Successfully....");
          
          this.setVisible(false);
          Product product = new Product();
          product.setVisible(true);
          
      }catch(Exception ex){
          JOptionPane.showMessageDialog(null,ex.getMessage());
      }
    }
   
    private void category(){
        
        try {  
            Class.forName("com.mysql.jdbc.Driver");  
            conn= DriverManager.getConnection(db,user,password);  
            Statement st = conn.createStatement();
            ResultSet r=st.executeQuery("select name from categories");
            
            while (r.next()) { 
                     jComboBox1.addItem(r.getString("name"));
                         
            }
                conn.close();
                
           } catch (Exception e) {  
                    JOptionPane.showMessageDialog(null,"Failed to Connect to Database","Error Connection", JOptionPane.WARNING_MESSAGE);                     
        }        
    }
 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Model Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 90, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Weight :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 90, 26));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Size :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 90, 25));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Category :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 90, 29));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Raw Material :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, 27));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 39, 234, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Quantity :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 90, 32));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Specification :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 90, 36));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 234, 40));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 234, 40));

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 240, 40));

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 240, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("ADD");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 72, 34));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 720, 10));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.setActionCommand("ADD");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 70, 40));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 240, 40));

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 240, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 130, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTextField1.getText().length()==0 || jTextField2.getText().length() == 0 || jTextField3.getText().length()==0 )  // Checking for empty field
            
                    JOptionPane.showMessageDialog(null, "Please, Fill Empty Text!!");
    
            else{
                
                    prodCode = jTextField1.getText();   // Collecting the input
                    String weight = jTextField2.getText();
                    String size = jTextField3.getText();
                   
                try{
                    Query("insert into product (ProdCode,Weight,Size)"
                            + "values('"+prodCode+"','"+weight+"','"+size+"')");
                  }
                    catch(Exception e){
                        e.printStackTrace();
                    }
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if( jComboBox1.getSelectedItem().toString().length()==0 || jComboBox2.getSelectedItem().toString().length()==0)  // Checking for empty field
                
                    JOptionPane.showMessageDialog(null, "Please, Fill Empty Text!!");
        
        else if (jTextField4.getText().length()==0 )
            
                     JOptionPane.showMessageDialog(null, "Please, Fill Empty Text!!");
            else{
            
                String category = jComboBox1.getSelectedItem().toString();
                String item = jComboBox2.getSelectedItem().toString();
                String qty = jTextField4.getText();
                
                
                try{
                    Query("insert into product_raw (ItemCode, ProdCode, Qty)"
                            + "values('"+item+"','"+prodCode+"','"+qty+"')");
                  }
                    catch(Exception e){
                        e.printStackTrace();
                    }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
            
        String category = (String) jComboBox1.getSelectedItem();
        //System.out.println("cat----"+category);
         try {
                Class.forName("com.mysql.jdbc.Driver");  
                conn= DriverManager.getConnection(db,user,password);  
                Statement st = conn.createStatement();
                ResultSet r=st.executeQuery("select ItemCode from rawmaterial where Category='"+category+"'");
                //System.out.println("**********"+jComboBox1.getSelectedItem());
                System.out.println("-----------");
                while (r.next()) { 
                     jComboBox2.addItem(r.getString("ItemCode"));                       
            }    
                //Object o = r.get(category);
                conn.close();
                
            }catch(Exception e){
                e.printStackTrace();
            }
            //Object o = r.get(category); 
    }//GEN-LAST:event_jComboBox1ActionPerformed
            //DefaultListModel dim3 = new DefaultListModel();
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
     
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
        try {
                Class.forName("com.mysql.jdbc.Driver");  
                conn= DriverManager.getConnection(db,user,password);  
                Statement st = conn.createStatement();
                ResultSet r=st.executeQuery("select ItemCode from rawmaterial where Category="+jComboBox1.getSelectedItem());
                System.out.println("**********"+jComboBox1.getSelectedItem());
                while (r.next()) { 
                     jComboBox2.addItem(r.getString("ItemCode"));                       
            }    
                //Object o = r.get(category);
                conn.close();
                
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_jComboBox1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
